Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
